[package]
name = "record"
version = "0.1.0"
edition = "2021"

[features]
vec = []
formulas = []
obj = ["forces"]
forces = []
event_loop = []
full = ["vec", "formulas", "obj", "forces", "event_loop"]

[dependencies]
