[package]
name = "record"
version = "0.1.0"
edition = "2021"

[features]
vec = []
formulas = []
obj = ["forces", "vec"]
forces = []
event_loop = []
collision = ["obj"]
full = ["vec", "formulas", "obj", "forces", "event_loop", "collision"]


[dependencies]
