name: Release workflow for motion

on:
  push:
    paths-ignore:
      - ".github/"
      - "release.toml"
      - "LICENSE"
      - "Readme.md"
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install cargo-release
        run: cargo install cargo-release

      - name: Login to crates.io
        uses: actions-rs/meta@v1
        with:
          crates-io-token: ${{ secrets.CRATESTOKEN }}

      - name: Release crate
        run: cargo release --workspace
